### ISSUE TITLE
again with odd issue

### ISSUE THREAD

**Issue by Hellcode48** [alekso56/MagicLoot3#4]
Here is the output in the console

Error occurred while enabling MagicLoot v3.0 (Is it up to date?)
java.lang.NullPointerException
    at me.mrCookieSlime.MagicLoot.MagicLoot.loadRuin(MagicLoot.java:317) ~[?:?]
    at me.mrCookieSlime.MagicLoot.MagicLoot.setupConfigs(MagicLoot.java:110) ~[?:?]
    at me.mrCookieSlime.MagicLoot.main.onEnable(main.java:60) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by alekso56** [comment]
Try building again.

**Comment by Hellcode48** [comment]
alright, here you go

java.lang.NullPointerException: Jar integrity compromised, did not find "schematics/GasStation.schematic" in the jar.
    at me.mrCookieSlime.MagicLoot.MagicLoot.loadRuin(MagicLoot.java:325) ~[?:?]
    at me.mrCookieSlime.MagicLoot.MagicLoot.setupConfigs(MagicLoot.java:110) ~[?:?]
    at me.mrCookieSlime.MagicLoot.main.onEnable(main.java:60) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by alekso56** [comment]
Please build the jar properly,, check that you are using maven to build and that the schematics are present in the jar file.

**Comment by Hellcode48** [comment]
I use the command mvn clean install, do I just use mvn install?

**Comment by alekso56** [comment]
The command is correct, but you do not have the schematic files in the jar. :p

**Comment by Hellcode48** [comment]
do I just add the schematics into the jar from the source code

**Comment by Hellcode48** [comment]
ok, so it loaded when I did that, but heres a few bugs:

![Image of issue](https://sc-cdn.scaleengine.net/i/5e87b80a22d97835296c90a899929114.jpg)

Could not pass event ChunkPopulateEvent to MagicLoot v3.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:986) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.Chunk.loadNearby(Chunk.java:939) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:172) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:139) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:119) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.loadChunk(CraftWorld.java:262) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at com.minelazz.epicworldgenerator.structures.StructureObject.a(StructureObject.java:75) [EpicWorldGenerator.jar:?]
    at com.minelazz.epicworldgenerator.biome.EpicBiome.a(EpicBiome.java:387) [EpicWorldGenerator.jar:?]
    at com.minelazz.epicworldgenerator.nativeAPI.implementations.v1_10_R1.generator.b.recreateStructures(b.java:337) [EpicWorldGenerator.jar:?]
    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:964) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.Chunk.loadNearby(Chunk.java:939) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:172) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:139) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:119) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.loadChunk(CraftWorld.java:262) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at com.minelazz.epicworldgenerator.structures.StructureObject.a(StructureObject.java:75) [EpicWorldGenerator.jar:?]
    at com.minelazz.epicworldgenerator.biome.EpicBiome.a(EpicBiome.java:387) [EpicWorldGenerator.jar:?]
    at com.minelazz.epicworldgenerator.nativeAPI.implementations.v1_10_R1.generator.b.recreateStructures(b.java:337) [EpicWorldGenerator.jar:?]
    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:964) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.Chunk.loadNearby(Chunk.java:939) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:172) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:139) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.PlayerChunk.a(PlayerChunk.java:112) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.PlayerChunkMap.flush(PlayerChunkMap.java:166) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:257) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:783) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_101]
    at me.mrCookieSlime.MagicLoot.RuinBuilder.buildRuin(RuinBuilder.java:38) ~[?:?]
    at me.mrCookieSlime.MagicLoot.MLListener.onRuinGenerate(MLListener.java:66) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor484.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
    ... 35 more

**Comment by alekso56** [comment]
I tried fixing up the maven stuff also fixed the bugs, try rebuilding.

**Comment by Hellcode48** [comment]
YES! YOU DID IT, its working, thanks man :D

**Comment by RoboMWM** [comment]
Well I just built a couple days ago (using `mvn package`) with commit https://github.com/alekso56/MagicLoot3/commit/dca0163d7634a38065f4b8523e0726670eeee147

Still getting a similar issue onEnable:

```
[00:39:59] [Server thread/INFO]: [MagicLoot] Enabling MagicLoot v3.0
[00:39:59] [Server thread/WARN]: [MagicLoot] Error saving buildings, they are not present in the jar!
[00:39:59] [Server thread/ERROR]: Error occurred while enabling MagicLoot v3.0 (Is it up to date?)
java.lang.NullPointerException
	at me.mrCookieSlime.MagicLoot.RuinBuilder.loadRuins(RuinBuilder.java:36) ~[?:?]
	at me.mrCookieSlime.MagicLoot.main.onEnable(main.java:66) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1045]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
[00:39:59] [Server thread/INFO]: [MagicLoot] Disabling MagicLoot v3.0
[00:39:59] [Server thread/ERROR]: Error occurred while disabling MagicLoot v3.0 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at me.mrCookieSlime.MagicLoot.main.onDisable(main.java:127) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1045]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
	at me.mrCookieSlime.MagicLoot.ItemManager.<clinit>(ItemManager.java:51) ~[?:?]
	... 13 more
```
If you'd rather have me create a new issue I can.
