### ISSUE TITLE
NPE due to buildings not being present in jar

### ISSUE THREAD

**Issue by RoboMWM** [alekso56/MagicLoot3#6]
If we have to do more than just `mvn package` can you please detail this in the readme or similar?

From #4:

Well I just built a couple days ago (using `mvn package`) with commit https://github.com/alekso56/MagicLoot3/commit/dca0163d7634a38065f4b8523e0726670eeee147

Still getting a similar issue onEnable:

```
[00:39:59] [Server thread/INFO]: [MagicLoot] Enabling MagicLoot v3.0
[00:39:59] [Server thread/WARN]: [MagicLoot] Error saving buildings, they are not present in the jar!
[00:39:59] [Server thread/ERROR]: Error occurred while enabling MagicLoot v3.0 (Is it up to date?)
java.lang.NullPointerException
	at me.mrCookieSlime.MagicLoot.RuinBuilder.loadRuins(RuinBuilder.java:36) ~[?:?]
	at me.mrCookieSlime.MagicLoot.main.onEnable(main.java:66) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1045]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
[00:39:59] [Server thread/INFO]: [MagicLoot] Disabling MagicLoot v3.0
[00:39:59] [Server thread/ERROR]: Error occurred while disabling MagicLoot v3.0 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at me.mrCookieSlime.MagicLoot.main.onDisable(main.java:127) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1045]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
	at me.mrCookieSlime.MagicLoot.ItemManager.<clinit>(ItemManager.java:51) ~[?:?]
	... 13 more
```

**Comment by RoboMWM** [comment]
The only schematic present in `buildings` is `Lost_Library.schematic`

**Comment by RoboMWM** [comment]
Alright, looked into this a little more, and it appears that instance#getResource is returning null even if said resource exists in the jar file. The moment I deleted the schematics folder in `plugins/MagicLoot`, it also whined about schematics not being present in the jar file.

@alekso56 This is likely because you are trying to get a folder as a resource? Try using the direct file path for each instead. (Looking at the history shows quite a number of issues trying to get this copied over, lol.)

**Comment by RoboMWM** [comment]
For anyone else having this issue, the current solution right now is to copy the buildings and schematics folder from here https://github.com/alekso56/MagicLoot3/tree/master/src/main/resources into your `plugins/MagicLoot` folder.
